name: web_date_picker_plus
description: Provides a date picker rendering library for web application development.
homepage: https://github.com/charcoast/web_date_picker_plus.git
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
